---
name: Tiny HTTPD Server Docker Image

'on':
  push:

  pull_request:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the timestamp to use.
        id: v2
        run: echo "timestamp=$(cat GITHUB_SHA:0:12)" >> $GITHUB_OUTPUT

      - name: Build the Docker image.
        uses: docker/build-push-action@v5
        with:
          build-args: |
            THTTPD_VERSION=${{ steps.v1.outputs.version }}
          tags: dcjulian29/httpd:${{ steps.v1.outputs.version }}-${{ steps.v2.outputs.timestamp }}

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Release Image
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub.
        uses: docker/login-action@v3
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push the Docker image.
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            THTTPD_VERSION=${{ steps.v1.outputs.version }}
          tags: |
            dcjulian29/httpd:${{ steps.v1.outputs.version }}
            dcjulian29/httpd:latest
